describe('util', function()
  it('offset_to_position offset 0', function()
    local util = require('lint.util')
    local position = util.offset_to_position({'foo', 'bar'}, 0)
    assert.are.same(position, { line = 0, character = 0 })
  end)
  it('offset_to_position with offset pointing to second line', function()
    local util = require('lint.util')
    local position = util.offset_to_position({'foo', 'bar xy'}, 3)
    assert.are.same(position, { line = 1, character = 0 })
  end)
  it('offset_to_position with offset pointing to second word in second line', function()
    local util = require('lint.util')
    local position = util.offset_to_position({'foo', 'bar xy'}, 7)
    assert.are.same(position, { line = 1, character = 4 })
  end)
end)
