describe("linter.checkstyle", function()
  local checkstyle = require("lint.linters.checkstyle")

  local parser = require("lint.parser").for_sarif(
    checkstyle.diagnostic_skeleton,
    vim.tbl_extend("force", {}, checkstyle.sarif_config, {
      fname_to_bufnr = function(fname)
        return fname == "/home/someuser/Downloads/foo.java" and 1 or 42
      end,
    })
  )

  describe("when given a SARIF log in JSON format, generated by checkstyle", function()
    it("can parse the log", function()
      local result = parser(
        [[
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "downloadUri": "https://github.com/checkstyle/checkstyle/releases/",
          "fullName": "Checkstyle",
          "informationUri": "https://checkstyle.org/",
          "language": "en",
          "name": "Checkstyle",
          "organization": "Checkstyle",
          "rules": [
          ],
          "semanticVersion": "10.12.6",
          "version": "10.12.6"
        }
      },
      "results": [
        {
          "level": "warning",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/home/someuser/Downloads/foo.java"
                },
                "region": {
                  "startColumn": 7,
                  "startLine": 1
                }
              }
            }
          ],
          "message": {
            "text": "Type name 'foo' must match pattern '^[A-Z][a-zA-Z0-9]*$'."
          },
          "ruleId": "name.invalidPattern"
        },
        {
          "level": "warning",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/home/someuser/Downloads/foo.java"
                },
                "region": {
                  "startColumn": 3,
                  "startLine": 3
                }
              }
            }
          ],
          "message": {
            "text": "'METHOD_DEF' should be separated from previous line."
          },
          "ruleId": "empty.line.separator"
        },
        {
          "level": "warning",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/home/someuser/Downloads/foo.java"
                },
                "region": {
                  "startColumn": 15,
                  "startLine": 3
                }
              }
            }
          ],
          "message": {
            "text": "Method Name 'foo' must not equal the enclosing class name."
          },
          "ruleId": "method.name.equals.class.name"
        },
        {
          "level": "warning",
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/home/someuser/Downloads/foo.java"
                },
                "region": {
                  "startColumn": 19,
                  "startLine": 3
                }
              }
            }
          ],
          "message": {
            "text": "'(' is preceded with whitespace."
          },
          "ruleId": "ws.preceded"
        }
      ]
    }
  ]
}
]],
        1
      )

      assert.are.same(4, #result)

      assert.are.same({
        bufnr = 1,
        lnum = 0,
        col = 6,
        severity = vim.diagnostic.severity.WARN,
        message = "Type name 'foo' must match pattern '^[A-Z][a-zA-Z0-9]*$'.",
        source = "Checkstyle",
        code = "name.invalidPattern",
      }, result[1])

      assert.are.same({
        bufnr = 1,
        lnum = 2,
        col = 2,
        severity = vim.diagnostic.severity.WARN,
        message = "'METHOD_DEF' should be separated from previous line.",
        source = "Checkstyle",
        code = "empty.line.separator",
      }, result[2])

      assert.are.same({
        bufnr = 1,
        lnum = 2,
        col = 14,
        severity = vim.diagnostic.severity.WARN,
        message = "Method Name 'foo' must not equal the enclosing class name.",
        source = "Checkstyle",
        code = "method.name.equals.class.name",
      }, result[3])

      assert.are.same({
        bufnr = 1,
        lnum = 2,
        col = 18,
        severity = vim.diagnostic.severity.WARN,
        message = "'(' is preceded with whitespace.",
        source = "Checkstyle",
        code = "ws.preceded",
      }, result[4])
    end)
  end)
end)
